# Generated by Django 5.1.6 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
