# Generated by Django 5.1.6 on 2025-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_csvupload_completed_at_alter_csvupload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
